language: php

php:
- 5.4
- 5.3

branches:
  only:
    - master

env:
- DB=mysql
- DB=pgsql

before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

script: phpunit UnitTest/ --coverage-text --stderr
